### ISSUE TITLE
Release Facedancer 3.0.7

### ISSUE THREAD

**Issue by antoinevg** [greatscottgadgets/facedancer#117]
This is the tracking issue for the `facedancer` `3.0.4` release.

```[tasklist]
### Tasks not yet associated with an Issue or Pull Request
```

```[tasklist]
### Documentation
```

```[tasklist]
### Issues
```

```[tasklist]
### Review, merge or close outstanding pull requests
- [ ] https://github.com/greatscottgadgets/facedancer/pull/143
- [ ] https://github.com/greatscottgadgets/facedancer/pull/146
- [x] Update #143 to bump Python min version to 3.10
```
