### ISSUE TITLE
Release Facedancer 3.0.0

### ISSUE THREAD

**Issue by antoinevg** [greatscottgadgets/facedancer#79]
This is the tracking issue for the Facedancer 3.0.0 release.
```[tasklist]
### Tasks not yet associated with an Issue or Pull Request
- [x] Update Facedancer README.md for 3.0.0 release
- [x] s/FaceDancer/Facedancer
- [x] We need a unified mechanism for Facedancer&USBProxy to configure usb interface speeds for boards that support multiple speeds such as Cynthion.
- [x] modify rubberducky actions to make sense on all platforms
- [x] add a CHANGELOG
- [x] use sphinxcontrib.apidoc for api doc template generation
```

```[tasklist]
### Issues
- [ ] https://github.com/greatscottgadgets/Facedancer/issues/48
- [x] #51 (Fixed by #52)
- [ ] #59
- [ ] #65
```

```[tasklist]
### Review, merge or close outstanding pull requests
- [ ] https://github.com/greatscottgadgets/facedancer/pull/96
- [ ] https://github.com/greatscottgadgets/facedancer/pull/92
- [ ] https://github.com/greatscottgadgets/facedancer/pull/86
- [ ] #40
- [ ] #38
- [ ] #63
- [ ] #57
- [ ] #52
- [ ] #44
- [ ] https://github.com/greatscottgadgets/Facedancer/pull/80
- [ ] #78
- [ ] #68
- [ ] https://github.com/greatscottgadgets/facedancer/pull/89
```
