### ISSUE TITLE
Facedancer Roadmap

### ISSUE THREAD

**Issue by antoinevg** [greatscottgadgets/facedancer#97]
This is the tracking issue for the Facedancer 3.1.0 release.
```[tasklist]
### Tasks not yet associated with an Issue or Pull Request
- [ ] Consider supplementing the ftdi-echo example in favor of a canonical serial emulation which is not FTDI
- [ ] Add some USB High Speed examples
- [ ] Upgrade warning in device.py:send():286 to an Exception
- [ ] Remove transfer limit on control IN transfers for both Cynthion and GreatFET.
```

```[tasklist]
### Issues
- [ ] #74
- [ ] #64
- [ ] #33
- [ ] https://github.com/greatscottgadgets/Facedancer/issues/15
- [ ] https://github.com/greatscottgadgets/facedancer/issues/87
- [ ] https://github.com/greatscottgadgets/facedancer/issues/90
- [ ] https://github.com/greatscottgadgets/facedancer/issues/114
```

```[tasklist]
### Review, merge or close outstanding pull requests
- [ ] https://github.com/greatscottgadgets/facedancer/pull/94
- [ ] https://github.com/greatscottgadgets/facedancer/pull/93
```
